package com.study.model;

import org.joda.time.DateTime;

public class ClActionStrategy {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.id
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.name
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.code
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.descr
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String descr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.min_gap
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private Short minGap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.daily_stop_action_hours
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String dailyStopActionHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.stop_action_hour_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String stopActionHourStrategy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.daily_max_action
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private Short dailyMaxAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.ext_attrs
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String extAttrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.type
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.create_time
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private DateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.create_person
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String createPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.modify_time
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private DateTime modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.modify_person
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String modifyPerson;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cl_action_strategy.flag
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    private String flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.id
     *
     * @return the value of cl_action_strategy.id
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.id
     *
     * @param id the value for cl_action_strategy.id
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.name
     *
     * @return the value of cl_action_strategy.name
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.name
     *
     * @param name the value for cl_action_strategy.name
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.code
     *
     * @return the value of cl_action_strategy.code
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.code
     *
     * @param code the value for cl_action_strategy.code
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.descr
     *
     * @return the value of cl_action_strategy.descr
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.descr
     *
     * @param descr the value for cl_action_strategy.descr
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setDescr(String descr) {
        this.descr = descr == null ? null : descr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.min_gap
     *
     * @return the value of cl_action_strategy.min_gap
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public Short getMinGap() {
        return minGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.min_gap
     *
     * @param minGap the value for cl_action_strategy.min_gap
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setMinGap(Short minGap) {
        this.minGap = minGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.daily_stop_action_hours
     *
     * @return the value of cl_action_strategy.daily_stop_action_hours
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getDailyStopActionHours() {
        return dailyStopActionHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.daily_stop_action_hours
     *
     * @param dailyStopActionHours the value for cl_action_strategy.daily_stop_action_hours
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setDailyStopActionHours(String dailyStopActionHours) {
        this.dailyStopActionHours = dailyStopActionHours == null ? null : dailyStopActionHours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.stop_action_hour_strategy
     *
     * @return the value of cl_action_strategy.stop_action_hour_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getStopActionHourStrategy() {
        return stopActionHourStrategy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.stop_action_hour_strategy
     *
     * @param stopActionHourStrategy the value for cl_action_strategy.stop_action_hour_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setStopActionHourStrategy(String stopActionHourStrategy) {
        this.stopActionHourStrategy = stopActionHourStrategy == null ? null : stopActionHourStrategy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.daily_max_action
     *
     * @return the value of cl_action_strategy.daily_max_action
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public Short getDailyMaxAction() {
        return dailyMaxAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.daily_max_action
     *
     * @param dailyMaxAction the value for cl_action_strategy.daily_max_action
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setDailyMaxAction(Short dailyMaxAction) {
        this.dailyMaxAction = dailyMaxAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.ext_attrs
     *
     * @return the value of cl_action_strategy.ext_attrs
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getExtAttrs() {
        return extAttrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.ext_attrs
     *
     * @param extAttrs the value for cl_action_strategy.ext_attrs
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setExtAttrs(String extAttrs) {
        this.extAttrs = extAttrs == null ? null : extAttrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.type
     *
     * @return the value of cl_action_strategy.type
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.type
     *
     * @param type the value for cl_action_strategy.type
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.create_time
     *
     * @return the value of cl_action_strategy.create_time
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public DateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.create_time
     *
     * @param createTime the value for cl_action_strategy.create_time
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setCreateTime(DateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.create_person
     *
     * @return the value of cl_action_strategy.create_person
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getCreatePerson() {
        return createPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.create_person
     *
     * @param createPerson the value for cl_action_strategy.create_person
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setCreatePerson(String createPerson) {
        this.createPerson = createPerson == null ? null : createPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.modify_time
     *
     * @return the value of cl_action_strategy.modify_time
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public DateTime getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.modify_time
     *
     * @param modifyTime the value for cl_action_strategy.modify_time
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setModifyTime(DateTime modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.modify_person
     *
     * @return the value of cl_action_strategy.modify_person
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getModifyPerson() {
        return modifyPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.modify_person
     *
     * @param modifyPerson the value for cl_action_strategy.modify_person
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setModifyPerson(String modifyPerson) {
        this.modifyPerson = modifyPerson == null ? null : modifyPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cl_action_strategy.flag
     *
     * @return the value of cl_action_strategy.flag
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cl_action_strategy.flag
     *
     * @param flag the value for cl_action_strategy.flag
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }
}