package com.study.model;

import java.util.ArrayList;
import java.util.List;
import org.joda.time.DateTime;

public class ClActionStrategyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public ClActionStrategyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> createTimeCriteria;

        protected List<Criterion> modifyTimeCriteria;

        protected List<Criterion> allCriteria;

        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
            createTimeCriteria = new ArrayList<Criterion>();
            modifyTimeCriteria = new ArrayList<Criterion>();
        }

        public List<Criterion> getCreateTimeCriteria() {
            return createTimeCriteria;
        }

        protected void addCreateTimeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            createTimeCriteria.add(new Criterion(condition, value, "com.bdms.ibatis.typeHandler.JodaDateTime2TimestampTypeHandler"));
            allCriteria = null;
        }

        protected void addCreateTimeCriterion(String condition, DateTime value1, DateTime value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            createTimeCriteria.add(new Criterion(condition, value1, value2, "com.bdms.ibatis.typeHandler.JodaDateTime2TimestampTypeHandler"));
            allCriteria = null;
        }

        public List<Criterion> getModifyTimeCriteria() {
            return modifyTimeCriteria;
        }

        protected void addModifyTimeCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            modifyTimeCriteria.add(new Criterion(condition, value, "com.bdms.ibatis.typeHandler.JodaDateTime2TimestampTypeHandler"));
            allCriteria = null;
        }

        protected void addModifyTimeCriterion(String condition, DateTime value1, DateTime value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            modifyTimeCriteria.add(new Criterion(condition, value1, value2, "com.bdms.ibatis.typeHandler.JodaDateTime2TimestampTypeHandler"));
            allCriteria = null;
        }

        public boolean isValid() {
            return criteria.size() > 0
                || createTimeCriteria.size() > 0
                || modifyTimeCriteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            if (allCriteria == null) {
                allCriteria = new ArrayList<Criterion>();
                allCriteria.addAll(criteria);
                allCriteria.addAll(createTimeCriteria);
                allCriteria.addAll(modifyTimeCriteria);
            }
            return allCriteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
            allCriteria = null;
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
            allCriteria = null;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andDescrIsNull() {
            addCriterion("descr is null");
            return (Criteria) this;
        }

        public Criteria andDescrIsNotNull() {
            addCriterion("descr is not null");
            return (Criteria) this;
        }

        public Criteria andDescrEqualTo(String value) {
            addCriterion("descr =", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotEqualTo(String value) {
            addCriterion("descr <>", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThan(String value) {
            addCriterion("descr >", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrGreaterThanOrEqualTo(String value) {
            addCriterion("descr >=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThan(String value) {
            addCriterion("descr <", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLessThanOrEqualTo(String value) {
            addCriterion("descr <=", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrLike(String value) {
            addCriterion("descr like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotLike(String value) {
            addCriterion("descr not like", value, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrIn(List<String> values) {
            addCriterion("descr in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotIn(List<String> values) {
            addCriterion("descr not in", values, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrBetween(String value1, String value2) {
            addCriterion("descr between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andDescrNotBetween(String value1, String value2) {
            addCriterion("descr not between", value1, value2, "descr");
            return (Criteria) this;
        }

        public Criteria andMinGapIsNull() {
            addCriterion("min_gap is null");
            return (Criteria) this;
        }

        public Criteria andMinGapIsNotNull() {
            addCriterion("min_gap is not null");
            return (Criteria) this;
        }

        public Criteria andMinGapEqualTo(Short value) {
            addCriterion("min_gap =", value, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapNotEqualTo(Short value) {
            addCriterion("min_gap <>", value, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapGreaterThan(Short value) {
            addCriterion("min_gap >", value, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapGreaterThanOrEqualTo(Short value) {
            addCriterion("min_gap >=", value, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapLessThan(Short value) {
            addCriterion("min_gap <", value, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapLessThanOrEqualTo(Short value) {
            addCriterion("min_gap <=", value, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapIn(List<Short> values) {
            addCriterion("min_gap in", values, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapNotIn(List<Short> values) {
            addCriterion("min_gap not in", values, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapBetween(Short value1, Short value2) {
            addCriterion("min_gap between", value1, value2, "minGap");
            return (Criteria) this;
        }

        public Criteria andMinGapNotBetween(Short value1, Short value2) {
            addCriterion("min_gap not between", value1, value2, "minGap");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursIsNull() {
            addCriterion("daily_stop_action_hours is null");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursIsNotNull() {
            addCriterion("daily_stop_action_hours is not null");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursEqualTo(String value) {
            addCriterion("daily_stop_action_hours =", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursNotEqualTo(String value) {
            addCriterion("daily_stop_action_hours <>", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursGreaterThan(String value) {
            addCriterion("daily_stop_action_hours >", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursGreaterThanOrEqualTo(String value) {
            addCriterion("daily_stop_action_hours >=", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursLessThan(String value) {
            addCriterion("daily_stop_action_hours <", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursLessThanOrEqualTo(String value) {
            addCriterion("daily_stop_action_hours <=", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursLike(String value) {
            addCriterion("daily_stop_action_hours like", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursNotLike(String value) {
            addCriterion("daily_stop_action_hours not like", value, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursIn(List<String> values) {
            addCriterion("daily_stop_action_hours in", values, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursNotIn(List<String> values) {
            addCriterion("daily_stop_action_hours not in", values, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursBetween(String value1, String value2) {
            addCriterion("daily_stop_action_hours between", value1, value2, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andDailyStopActionHoursNotBetween(String value1, String value2) {
            addCriterion("daily_stop_action_hours not between", value1, value2, "dailyStopActionHours");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyIsNull() {
            addCriterion("stop_action_hour_strategy is null");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyIsNotNull() {
            addCriterion("stop_action_hour_strategy is not null");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyEqualTo(String value) {
            addCriterion("stop_action_hour_strategy =", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyNotEqualTo(String value) {
            addCriterion("stop_action_hour_strategy <>", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyGreaterThan(String value) {
            addCriterion("stop_action_hour_strategy >", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyGreaterThanOrEqualTo(String value) {
            addCriterion("stop_action_hour_strategy >=", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyLessThan(String value) {
            addCriterion("stop_action_hour_strategy <", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyLessThanOrEqualTo(String value) {
            addCriterion("stop_action_hour_strategy <=", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyLike(String value) {
            addCriterion("stop_action_hour_strategy like", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyNotLike(String value) {
            addCriterion("stop_action_hour_strategy not like", value, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyIn(List<String> values) {
            addCriterion("stop_action_hour_strategy in", values, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyNotIn(List<String> values) {
            addCriterion("stop_action_hour_strategy not in", values, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyBetween(String value1, String value2) {
            addCriterion("stop_action_hour_strategy between", value1, value2, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andStopActionHourStrategyNotBetween(String value1, String value2) {
            addCriterion("stop_action_hour_strategy not between", value1, value2, "stopActionHourStrategy");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionIsNull() {
            addCriterion("daily_max_action is null");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionIsNotNull() {
            addCriterion("daily_max_action is not null");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionEqualTo(Short value) {
            addCriterion("daily_max_action =", value, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionNotEqualTo(Short value) {
            addCriterion("daily_max_action <>", value, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionGreaterThan(Short value) {
            addCriterion("daily_max_action >", value, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionGreaterThanOrEqualTo(Short value) {
            addCriterion("daily_max_action >=", value, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionLessThan(Short value) {
            addCriterion("daily_max_action <", value, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionLessThanOrEqualTo(Short value) {
            addCriterion("daily_max_action <=", value, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionIn(List<Short> values) {
            addCriterion("daily_max_action in", values, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionNotIn(List<Short> values) {
            addCriterion("daily_max_action not in", values, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionBetween(Short value1, Short value2) {
            addCriterion("daily_max_action between", value1, value2, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andDailyMaxActionNotBetween(Short value1, Short value2) {
            addCriterion("daily_max_action not between", value1, value2, "dailyMaxAction");
            return (Criteria) this;
        }

        public Criteria andExtAttrsIsNull() {
            addCriterion("ext_attrs is null");
            return (Criteria) this;
        }

        public Criteria andExtAttrsIsNotNull() {
            addCriterion("ext_attrs is not null");
            return (Criteria) this;
        }

        public Criteria andExtAttrsEqualTo(String value) {
            addCriterion("ext_attrs =", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsNotEqualTo(String value) {
            addCriterion("ext_attrs <>", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsGreaterThan(String value) {
            addCriterion("ext_attrs >", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsGreaterThanOrEqualTo(String value) {
            addCriterion("ext_attrs >=", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsLessThan(String value) {
            addCriterion("ext_attrs <", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsLessThanOrEqualTo(String value) {
            addCriterion("ext_attrs <=", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsLike(String value) {
            addCriterion("ext_attrs like", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsNotLike(String value) {
            addCriterion("ext_attrs not like", value, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsIn(List<String> values) {
            addCriterion("ext_attrs in", values, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsNotIn(List<String> values) {
            addCriterion("ext_attrs not in", values, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsBetween(String value1, String value2) {
            addCriterion("ext_attrs between", value1, value2, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andExtAttrsNotBetween(String value1, String value2) {
            addCriterion("ext_attrs not between", value1, value2, "extAttrs");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(DateTime value) {
            addCreateTimeCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(DateTime value) {
            addCreateTimeCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(DateTime value) {
            addCreateTimeCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(DateTime value) {
            addCreateTimeCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(DateTime value) {
            addCreateTimeCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(DateTime value) {
            addCreateTimeCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<DateTime> values) {
            addCreateTimeCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<DateTime> values) {
            addCreateTimeCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(DateTime value1, DateTime value2) {
            addCreateTimeCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(DateTime value1, DateTime value2) {
            addCreateTimeCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIsNull() {
            addCriterion("create_person is null");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIsNotNull() {
            addCriterion("create_person is not null");
            return (Criteria) this;
        }

        public Criteria andCreatePersonEqualTo(String value) {
            addCriterion("create_person =", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotEqualTo(String value) {
            addCriterion("create_person <>", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonGreaterThan(String value) {
            addCriterion("create_person >", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonGreaterThanOrEqualTo(String value) {
            addCriterion("create_person >=", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLessThan(String value) {
            addCriterion("create_person <", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLessThanOrEqualTo(String value) {
            addCriterion("create_person <=", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonLike(String value) {
            addCriterion("create_person like", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotLike(String value) {
            addCriterion("create_person not like", value, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonIn(List<String> values) {
            addCriterion("create_person in", values, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotIn(List<String> values) {
            addCriterion("create_person not in", values, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonBetween(String value1, String value2) {
            addCriterion("create_person between", value1, value2, "createPerson");
            return (Criteria) this;
        }

        public Criteria andCreatePersonNotBetween(String value1, String value2) {
            addCriterion("create_person not between", value1, value2, "createPerson");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNull() {
            addCriterion("modify_time is null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIsNotNull() {
            addCriterion("modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifyTimeEqualTo(DateTime value) {
            addModifyTimeCriterion("modify_time =", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotEqualTo(DateTime value) {
            addModifyTimeCriterion("modify_time <>", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThan(DateTime value) {
            addModifyTimeCriterion("modify_time >", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeGreaterThanOrEqualTo(DateTime value) {
            addModifyTimeCriterion("modify_time >=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThan(DateTime value) {
            addModifyTimeCriterion("modify_time <", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeLessThanOrEqualTo(DateTime value) {
            addModifyTimeCriterion("modify_time <=", value, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeIn(List<DateTime> values) {
            addModifyTimeCriterion("modify_time in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotIn(List<DateTime> values) {
            addModifyTimeCriterion("modify_time not in", values, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeBetween(DateTime value1, DateTime value2) {
            addModifyTimeCriterion("modify_time between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyTimeNotBetween(DateTime value1, DateTime value2) {
            addModifyTimeCriterion("modify_time not between", value1, value2, "modifyTime");
            return (Criteria) this;
        }

        public Criteria andModifyPersonIsNull() {
            addCriterion("modify_person is null");
            return (Criteria) this;
        }

        public Criteria andModifyPersonIsNotNull() {
            addCriterion("modify_person is not null");
            return (Criteria) this;
        }

        public Criteria andModifyPersonEqualTo(String value) {
            addCriterion("modify_person =", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonNotEqualTo(String value) {
            addCriterion("modify_person <>", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonGreaterThan(String value) {
            addCriterion("modify_person >", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonGreaterThanOrEqualTo(String value) {
            addCriterion("modify_person >=", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonLessThan(String value) {
            addCriterion("modify_person <", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonLessThanOrEqualTo(String value) {
            addCriterion("modify_person <=", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonLike(String value) {
            addCriterion("modify_person like", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonNotLike(String value) {
            addCriterion("modify_person not like", value, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonIn(List<String> values) {
            addCriterion("modify_person in", values, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonNotIn(List<String> values) {
            addCriterion("modify_person not in", values, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonBetween(String value1, String value2) {
            addCriterion("modify_person between", value1, value2, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andModifyPersonNotBetween(String value1, String value2) {
            addCriterion("modify_person not between", value1, value2, "modifyPerson");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(String value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(String value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(String value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(String value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(String value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(String value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLike(String value) {
            addCriterion("flag like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotLike(String value) {
            addCriterion("flag not like", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<String> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<String> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(String value1, String value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(String value1, String value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_action_strategy
     *
     * @mbg.generated do_not_delete_during_merge Fri Sep 23 14:36:33 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cl_action_strategy
     *
     * @mbg.generated Fri Sep 23 14:36:33 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}